# ms1-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsmicroservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productsmicroservice
  template:
    metadata:
      labels:
        app: productsmicroservice
    spec:
      containers:
        - name: productsmicroservice-container
          image: saltytoona/productsmicroservice:latest
          ports:
            - containerPort: 30217
---
apiVersion: v1
kind: Service
metadata:
  name: productsmicroservice
spec:
  selector:
    app: productsmicroservice
  type: NodePort
  ports:
    - protocol: TCP
      port: 30217
      targetPort: 30217
      nodePort: 30217
