name: On Merge in Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  docker-configuration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME }}/productsmicroservice:latest .
        working-directory: .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{secrets.DOCKERHUB_USERNAME }}/productsmicroservice:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
      - name: Push Docker image to DockerHub
        run: docker push ${{secrets.DOCKERHUB_USERNAME }}/productsmicroservice:latest
